# Generated by Django 4.0.1 on 2022-01-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_request', '0003_alter_requestpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestpost',
            options={'permissions': [('view_all_request_post', 'Can view all request posts'), ('approve_request_post', 'Can approve request post')]},
        ),
    ]
